### ISSUE TITLE
Authentication error when uploading a dataset 

### ISSUE THREAD

**Issue by EthanHargrove** [digiLab-ai/twinLab-Interface#1]
**Describe the bug**
When following the Getting Started guide in the documentation, a 'bad auth : authentication failed' error message is encountered. This error message is received when using a `.env file` and when `using set_api_key()`.

**What were you trying to do?**
The error occurred when trying to upload the test dataset.

**What was the expected behaviour?**
A return indicated a successful upload.

**What actually happened?**
A `Non-success status code` print and a raised exception <br><br>`Exception: Error Code: 401 - {'detail': "bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'}"}`

**To Reproduce**
Running:
```
echo "TWINLAB_API_KEY=<my_api_key>" > .env
```

```
import twinlab as tl
import pandas as pd

df = pd.DataFrame({"X": [1, 2, 3, 4], "y": [1, 4, 9, 16]})
dataset = tl.Dataset("test-data")
dataset.upload(df)
```

**Screenshots**
The return when importing (with repository name redacted):
![Screenshot 2024-06-12 at 12 09 18 pm](https://github.com/digiLab-ai/twinLab-Interface/assets/91437527/07ca1fde-af62-48bd-9777-cc4d191e0a8e)

The returned error:
![Screenshot 2024-06-12 at 12 07 37 pm](https://github.com/digiLab-ai/twinLab-Interface/assets/91437527/f250ff82-f7d1-465a-bb84-f3c983f40de0)

**Additional context**
The code is being run in a Jupyter notebook on a Mac

**Comment by alexander-mead** [comment]
Thanks for your issue. We currently have the same problem on our end (so it's not specific to your account). We're working on a fix now and we will get back to you as soon as possible.

**Comment by alexander-mead** [comment]
That should be fixed now. We lost connection to the database, but we've restored it now. Please let me know if anything else goes wrong!
